
---

services:
  traefik:
    container_name: traefik
    image: traefik:v2.9
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      #- "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@ntuscse.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      cms_network:
        ipv4_address: 10.5.0.99
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
        #labels:
        #- "traefik.enable=true"
        #- "traefik.http.routers.traefik.rule=Host(`traefik.staging.ntuscse.com`)"
      #- "traefik.http.routers.traefik.entrypoints=web"

  cms:
    container_name: cms
    image: ghcr.io/ntuscse/website/cms:latest
    networks:
      cms_network:
        ipv4_address: 10.5.0.2
    env_file:
      - cms.env
    restart: always
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms.rule=Host(`cms.staging.ntuscse.com`, `13.213.116.60`, `localhost`)"
      - "traefik.http.routers.cms.entrypoints=websecure"
      - "traefik.http.routers.cms.tls.certresolver=myresolver"

  mongo:
    container_name: mongo
    image: mongo:latest
    networks:
      cms_network:
        ipv4_address: 10.5.0.3
    volumes:
      - ./db_data:/data/db
    restart: always

networks:
  cms_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
