name: CD Staging

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-cms:
    name: Build CMS Docker Image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./apps/cms/docker/staging/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/website/cms:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/website/cms:latest


  build-merch:
    name: Build Merch Docker Image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./apps/merch/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/website/merch:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/website/merch:latest


  build-web:
    name: Build Web next.js app
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Build web
        run: yarn turbo run build --filter=web

      - name: Cache CD Staging workflow for dependent jobs
        uses: actions/cache/save@v3
        with:
          path: .
          key: CD-Staging-${{ runner.os }}-${{ github.ref }}-${{ github.run_id }}

  deploy-to-staging:
    name: Deploy To Staging
    runs-on: ubuntu-22.04
    needs:
      - build-cms
      - build-merch
      - build-web
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy and run docker images
        env:
          PRIVATE_KEY: ${{ secrets.STAGING_EC2_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.STAGING_EC2_HOSTNAME  }}
          USER_NAME: ${{ secrets.STAGING_EC2_USERNAME  }}
        run: |
          pwd
          ls
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key ./deployments/staging/docker-compose.yml ${USER_NAME}@${HOSTNAME}:/home/ubuntu/deployment
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/deployment &&
            docker system prune --force &&
            docker compose pull &&
            docker compose up -d
          '

  deploy-to-vercel:
    name: Deploy To Staging
    runs-on: ubuntu-22.04
    needs:
      - build-cms
      - build-merch
      - build-web
    steps:
      - name: Get build cache
        uses: actions/cache/restore@v3
        with:
          path: .
          key: CD-Staging-${{ runner.os }}-${{ github.ref }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Copy Build Artifacts to .vercel dir
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy-to-vercel
        run: |
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$DEPLOYMENT_URL" dev.ntuscse.com
